name: Build For Reverse Proxy

on:
  push:
    branches: beta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
    steps:
      - uses: actions/checkout@v1

      - name: Delete branch
        uses: dawidd6/action-delete-branch@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: build_reverse_proxy

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm run build prod
        run: |
          npm ci
          npm run buildPourReverse

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build_reverse_proxy
          FOLDER: dist
          CLEAN: true
